//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WL_CapstonePrototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanSet
    {
        public int Id { get; set; }
        public string ScanTime { get; set; }
        public int GarbageId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public int UsersId { get; set; }
    
        public virtual AddressSet AddressSet { get; set; }
        public virtual GarbageSet GarbageSet { get; set; }
        public virtual Users Users { get; set; }
    }
}
